apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: kafka-topics
        image: confluentinc/cp-kafka:7.5.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Kafka to be ready..."
          cub kafka-ready -b kafka-service.kafka.svc.cluster.local:9092 1 30
          
          echo "Creating topics..."
          kafka-topics --create --if-not-exists \
            --bootstrap-server kafka-service.kafka.svc.cluster.local:9092 \
            --topic restaurant-events \
            --partitions 3 \
            --replication-factor 1
          
          kafka-topics --create --if-not-exists \
            --bootstrap-server kafka-service.kafka.svc.cluster.local:9092 \
            --topic processed-events \
            --partitions 3 \
            --replication-factor 1
          
          echo "Topics created successfully"
          kafka-topics --list --bootstrap-server kafka-service.kafka.svc.cluster.local:9092
      restartPolicy: Never
  backoffLimit: 4