apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-app-config
  namespace: spark
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.kafka.svc.cluster.local:9092"
  INPUT_TOPIC: "restaurant-events"
  OUTPUT_TOPIC: "processed-events"
  STARTING_OFFSETS: "latest"
  APP_NAME: "SparkStreamingProcessor"
  CHECKPOINT_LOCATION: "/tmp/checkpoint"
  TRIGGER_INTERVAL: "10 seconds"
  LOG_LEVEL: "INFO"
  PROCESSING_VERSION: "1.0.0"
  IS_KUBERNETES: "true"
  K8S_NAMESPACE: "spark"