apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kafka-spark-streaming
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "kafka-spark-streaming:latest"
  imagePullPolicy: Never  # Use local image in minikube
  mainApplicationFile: "/app/spark_streaming_app.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    labels:
      version: 3.5.0
    serviceAccount: spark
    env:
      - name: KAFKA_SERVERS
        value: "kafka-service.kafka.svc.cluster.local:9092"
      - name: INPUT_TOPIC
        value: "restaurant-events"
      - name: OUTPUT_TOPIC
        value: "processed-events"
  executor:
    cores: 1
    instances: 2
    memory: "1g"
    labels:
      version: 3.5.0
    env:
      - name: KAFKA_SERVERS
        value: "kafka-service.kafka.svc.cluster.local:9092"
      - name: INPUT_TOPIC
        value: "restaurant-events"
      - name: OUTPUT_TOPIC
        value: "processed-events"
  deps:
    packages:
      - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.16.1.jar"