apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/name: kafka-cluster-kafka
