apiVersion: v1
kind: Pod
metadata:
  name: spark-streaming-job
  namespace: spark
spec:
  serviceAccountName: spark
  restartPolicy: Never
  containers:
  - name: spark-streaming
    image: spark-kafka-streaming:latest
    imagePullPolicy: Never
    command:
    - /opt/spark/bin/spark-submit
    args:
    - --driver-memory
    - 1g
    - --executor-memory
    - 1g
    - /opt/spark/work-dir/spark_streaming_app.py
    env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"