# Custom values for Spark Operator Helm chart
webhook:
  enable: true
  #port: 8080

sparkJobNamespace: spark

serviceAccounts:
  spark:
    create: false
    name: spark
  sparkoperator:
    create: false
    name: spark-operator

controllerThreads: 10
resyncInterval: 30

enableBatchScheduler: false
enableMetrics: true

metrics:
  enable: true
  port: 10254
  endpoint: /metrics

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000